steps:
  deploy:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/showcase:/build
    commands:
      - git config --global --add safe.directory '*'
      - cd /build
      - git checkout prod
      - git pull origin prod
      - docker compose -f docker-compose.prod.yml up -d --build
    when:
      - event: push
        branch: prod
