// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMaxTournamentActionCounts = `-- name: GetMaxTournamentActionCounts :many
SELECT 
    t.type::text AS type,
    MAX(t.action_count) AS max_count
FROM (
    SELECT 
        ma.actor_id, 
        ma.type, 
        COUNT(*) AS action_count
    FROM match_actions ma
    JOIN matches m ON ma.match_id = m.id
    WHERE m.tournament_id = $1
    GROUP BY ma.actor_id, ma.type
) t
GROUP BY t.type
`

type GetMaxTournamentActionCountsRow struct {
	Type     pgtype.Text
	MaxCount pgtype.Int8
}

func (q *Queries) GetMaxTournamentActionCounts(ctx context.Context, tournamentID pgtype.Text) ([]GetMaxTournamentActionCountsRow, error) {
	rows, err := q.db.Query(ctx, getMaxTournamentActionCounts, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaxTournamentActionCountsRow
	for rows.Next() {
		var i GetMaxTournamentActionCountsRow
		if err := rows.Scan(&i.Type, &i.MaxCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTournamentActionCounts = `-- name: GetPlayerTournamentActionCounts :many
SELECT 
    ma.type::text AS type,
    COUNT(*) AS count
FROM match_actions ma
JOIN matches m ON ma.match_id = m.id
WHERE ma.actor_id = $1 
  AND m.tournament_id = $2
GROUP BY ma.type
`

type GetPlayerTournamentActionCountsParams struct {
	ActorID      pgtype.Text
	TournamentID pgtype.Text
}

type GetPlayerTournamentActionCountsRow struct {
	Type  pgtype.Text
	Count pgtype.Int8
}

func (q *Queries) GetPlayerTournamentActionCounts(ctx context.Context, arg GetPlayerTournamentActionCountsParams) ([]GetPlayerTournamentActionCountsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerTournamentActionCounts, arg.ActorID, arg.TournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerTournamentActionCountsRow
	for rows.Next() {
		var i GetPlayerTournamentActionCountsRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTournamentMatchStats = `-- name: GetPlayerTournamentMatchStats :many
SELECT
    m.id AS match_id,
    m.date,
    COUNT(*) FILTER (WHERE ma.type = 'grab')     AS grab,
    COUNT(*) FILTER (WHERE ma.type = 'move')     AS move,
    COUNT(*) FILTER (WHERE ma.type = 'steal')    AS steal,
    COUNT(*) FILTER (WHERE ma.type = 'knockout') AS knockout,
    COUNT(*) FILTER (WHERE ma.type = 'score')    AS score
FROM matches m
JOIN match_actions ma
    ON ma.match_id = m.id
   AND ma.actor_id = $1
WHERE m.tournament_id = $2
GROUP BY m.id, m.date
ORDER BY m.date ASC
`

type GetPlayerTournamentMatchStatsParams struct {
	ActorID      pgtype.Text
	TournamentID pgtype.Text
}

type GetPlayerTournamentMatchStatsRow struct {
	MatchID  string
	Date     interface{}
	Grab     pgtype.Int8
	Move     pgtype.Int8
	Steal    pgtype.Int8
	Knockout pgtype.Int8
	Score    pgtype.Int8
}

func (q *Queries) GetPlayerTournamentMatchStats(ctx context.Context, arg GetPlayerTournamentMatchStatsParams) ([]GetPlayerTournamentMatchStatsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerTournamentMatchStats, arg.ActorID, arg.TournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerTournamentMatchStatsRow
	for rows.Next() {
		var i GetPlayerTournamentMatchStatsRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Date,
			&i.Grab,
			&i.Move,
			&i.Steal,
			&i.Knockout,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
